### ISSUE TITLE
Information about input

### ISSUE THREAD

**Issue by aniketbote** [JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models#4]
Can you provide information on how xtrain, y_train should be. There shapes/dimensions etc. It would be better if you added any end to end trainable example using any publicly available dataset. _tensorflow_datasets_ has many such datasets which you can use easily.

Thank you in advance

**Comment by JanMarcelKezmann** [comment]
Hi,
so first of all you can take a look at the examples section <a href="https://github.com/JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models/tree/master/examples">here</a>, there I currently have 3 examples using the publicly available dataset **CamVid**. Next to that I will upload the next couple of days a new example using the **caltech_birds2010** dataset from _tensorflow_datasets_ , so you can take a look how you can use data saved in the _tf.record__ format for segmenation. 

But to be more general you can take any publicly available or custom dataset and use the functionalities of Data Generators to define yourself a generator that can be used for fitting any of the given models. In that case the generator needs to yield an array, i.e. a _tf.tensor_, that has the dimensions **[BATCH_SIZE, HEIGHT, WIDTH, CHANNELS]**, where **CHANNELS** is in the case of the images either **1** or **3** depending on black/white or colored images and in the case of labels the number of classes you would like to segment including the background class, i.e. **len(CLASSES) + 1**.

But I think that this is especially well documented in the examples that's why I really recommed to take a look at them.
I hope that helps, if not just feel free to ask more questions.

**Comment by JanMarcelKezmann** [comment]
I have now added an example using the caltech_birds2010 dataset from _tensorflow_datasets_.

You can take a look <a href="https://github.com/JanMarcelKezmann/TensorFlow-Advanced-Segmentation-Models/blob/master/examples/TASM_Example_4.ipynb">here</a>.
